### ISSUE TITLE
cubic - quad-precision FP problem (ARM/RISCV)

### ISSUE THREAD

**Issue by mp-17** [embench/embench-iot#65]
Dear All,

I compiled the program **cubic** targeting both ARM and RISC-V.
This program uses the _long double_ type, which is interpreted in different ways by ARM and RISC-V: ARM interprets the _long double_ as just a _double_, so a 64-bit double-precision FP value (http://www.keil.com/support/man/docs/armcc/armcc_chr1359125009502.htm), whereas
RISC-V interprets the _long double_ as a quad-precision 128-bit quad-precision FP value (https://github.com/riscv/riscv-elf-psabi-doc/blob/master/riscv-elf.md#c-types).

I think the comparison between the sizes of the two codes is not completely fair: with real library support, the code size of the RISC-V program is dominated by the quad-precision FP emulation functions that are present only in the RISC-V code. 
With dummy libraries, the result is modified as well because RISC-V handles "larger" values than ARM, and values larger than 2*XLEN are passed by reference to the functions (https://github.com/riscv/riscv-elf-psabi-doc/blob/master/riscv-elf.md#floating-point-register-convention). I think this is why the RISC-V function <SolveCubic> uses the stack a lot with a consequent code size increasing.

Best regards,
Matteo

**Comment by jeremybennett** [comment]
Hi Matteo

This is a known issue. Long double is occasionally used, so it is right that it be benchmarked, although perhaps not in an integer benchmark suite.  It belongs more properly in the floating point benchmark suite.

This has been considered by the group in the past. It is the benchmark where RISC-V does by far the worst compared to Arm.  One consideration was that with the originators of Embench all having a RISC-V background, we were reluctant to drop the worst benchmark for RISC-V, since it could seem to undermine the independence of the benchmark.

An important aspect of Embench is that it will be renewed every two years, which gives a great opportunity to substitute some more appropriate benchmark programs.

Hope this explains the situation.


Jeremy
